<?php
//drupal_add_js('cmo_donation.js');

/**
 * Implementation of hook_permission() 
 */ 
function cmo_donation_permission() {
	$perm = array(
		'administer cmo donation module' => array(
			'title' => t('Administer CMO Donation module'),
			'description' => t('Perform Adminsteration task on CMO donation module'),
		),
	);
	
	return $perm;
}

/**
 * Implementation of hook_menu()
 */
function cmo_donation_menu(){
	$items = array();
	
	$items['admin/config/content/cmo_donation'] = array(
		'title' => 'Admin View CMO Donation',
		'description' => 'Report of CMO Donation',
		'page callback' => 'cmo_donation_report',
		'access callback' => TRUE
	);
	$items['cmo_donation'] = array(
		'title' => 'CMO Donation',
		'description' => 'A donation form for the CMO Jharkhand',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cmo_donation_form'),
		'access callback' => TRUE
	);
	
	return $items;
} 
/**
 * Implementation of Admin report section
 */
function cmo_donation_report(){
	print 'Work is on progress';
}

/**
 * Implementation of hook_form()
 */
function cmo_donation_form($form, &$form_state){
	
	$form['name'] = array(
		'#type' => 'textfield',
		'#title' => t('Name'),
		'#attributes' => array('placeholder' => t('Enter your full name..'),),
		'#size' => 30,
		'#maxlengh' => '128',
		'#weight' => 1,
		'#required' => TRUE
	);
	$form['i_am']= array(
		'#type' => 'radios',
		'#title' => t('I am'),
		'#options' => array(
			'indivi' => t('Individual'),
			'comp' => t('Company')),
		//'#default_value' => array('indivi',0), 
		'#weight' => 2,
		'#required' => TRUE
		

    );
	
	$form['pancard'] = array(
		'#type' => 'textfield',
		'#title' => t('PAN Number'),
		'#states' => array(
			'visible' => array(
				':input[name="i_am"]' => array('value' => 'indivi'),
			),
		),
		'#attributes' => array('placeholder' => 'XXXXXXXXXX','maxlength' => 10, 'size' => 30), 
		'#weight' => 3,
		//'#required' => TRUE
	);
	$form['tinnumber'] = array(
		'#type' => 'textfield',
		'#title' => t('TIN Number'),
		'#states' => array(
			'visible' => array(
				':input[name="i_am"]' => array('value' => 'comp'),
			),
		),
		'#attributes' => array('placeholder' => 'XXXXXXXXXXX','maxlength' => 11, 'size' => 30), 
		'#weight' => 4,
		//'#required' => TRUE
	);
	$form['mobile'] = array(
		'#type' => 'textfield',
		'#title' => t('Mobile'),
		'#attributes' => array('placeholder' => '7898878988', 'maxlength' => 10, 'size' => 30), 
		'#weight' => 5,
		'#required' => TRUE
	);
	$form['email_address']= array(
		'#type' => 'textfield',
		'#title' => t('Email'),
		'#attributes' => array('placeholder' => 'youremail@gmail.com'),
		'#weight' => 6,
		'#size' => 30,
		'#required' => TRUE
	);
	$form['quick_select_amount']= array(
		'#type' => 'radios',
		'#title' => t('Quick Select Amount'),
		'#options' => array(/*500,1000,2000,5000,10000,50000,100000,500000,1000000),*/
			500 => 500,
			1000 => 1000,
			2000 => 2000,
			5000 => 5000,
			10000 => 10000,
			500000 => 50000,
			100000 => 100000,
			500000 => 500000,
			1000000 => 1000000,
			),
		//'#default_value' => array('indivi',0), 
		'#weight' => 7,
		'#required' => FALSE
	);
	
	$form['custom_amount'] = array(
		'#type' => 'textfield',
		'#title' => t('Enter Custom Amount'),
		'#attributes' => array('placeholder' => t('Enter Amount(Minimum allowed amount is Rs. 100)'),'maxlength' => 10, 'size' => 60),
		'#weight' => 20,
		'#required' => TRUE
	);
	$form['payment_mode'] = array(
		'#type' => 'select',
		'#title' => t('Payment Mode'),
		'#options' => array(
			'debit_credit_card' => t('Debit/Credit Card'),
			'net_banking' => t('Net Banking'),
		),	
		//'#default_value' => array(0),
		'#weight' => 21,
		'#required' => TRUE
		
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#weight' => 22,
		'#value' => t('Submit')
	);
	return $form;
}
/**
 * Implementation of hook_form_validate()
 */
function cmo_donation_form_validate($form, &$form_state){
	
	$contact_info = $form_state['values']['mobile'];
		if (!is_numeric($contact_info)) {
			form_set_error('mobile',t('Please enter a valid mobile number eg.7878878887'));
		}
		
	$i_am = $form_state['values']['i_am'];
	$pancard = $form_state['values']['pancard'];
	$tin_number = $form_state['values']['tinnumber'];
	
		if((($i_am == 'indivi') && empty($pancard ))  ) {
			
			form_set_error('pancard',t('For Individual user it is compulsory to add PAN number'));
		}
		elseif(($i_am == 'indivi') && !is_numeric($pancard)){
			form_set_error('pancard',t('Please enter a valid PAN number'));
		}	
		if((($i_am == 'comp') && empty($tin_number )) ){
			form_set_error('tinnumber',t('For Company it is compulsory to add TIN number'));
		}
		elseif(($i_am == 'comp') && !is_numeric($tin_number)){
			form_set_error('pancard',t('Please enter a valid TIN number'));
		}	
	
	$amount = $form_state['values']['custom_amount'];
		if (!is_numeric($amount)) {
			form_set_error('custom_amount',t('Please enter a numeric value eg. 5000'));
		}	
	$valid_email = $form_state['values']['email_address'];
		if (!empty($valid_email) && !valid_email_address($valid_email)) {
			form_set_error('email', 'Sorry. Your email address, ' . $valid_email . ' , is not valid. Please submit a valid E-mail address.');
		}	
}
/**
 * Implementation of hook_form_submit()
 */
function cmo_donation_form_submit($form, &$form_state){
	$name = $form_state['values']['name'];
	$i_am = $form_state['values']['i_am'];
	$pancard = $form_state['values']['pancard'];
	$tin_number = $form_state['values']['tinnumber'];
	$contact_info = $form_state['values']['mobile'];
	$valid_email = $form_state['values']['email_address'];
	$quick_amount = $form_state['values']['quick_select_amount'];
	$amount = $form_state['values']['custom_amount'];
	$payment_mode = $form_state['values']['payment_mode'];
	
	$insert = db_insert('cmo_donation_table') // Table name no longer needs {}
		->fields(array(
		'name' => $name,
		'i_am' => $i_am,
		'pancard' => $pancard,
		'tinnumber' => $tin_number,
		'mobile' => $contact_info,
		'email' => $valid_email,
		'amount' => $amount,
		'payment_mode' => $payment_mode,
		
	))
->execute();
//dpm($nid);
	if($insert){
		 drupal_set_message('Thanks for your donation to CMO Jharkhand');
		
	}
} 

/**
 * Implementation of hook_views_api
 */

function cmo_donation_views_api(){
	return array(
		'api' => '3.0',
		'path' => drupal_get_path('module','cmo_donation').'/views',
	);
}



?>